In [1]:
import sys
import os
import pandas as pd
import numpy as np
import torch
import time

sys.path.append(os.path.abspath('../src'))

from sklearn.model_selection import train_test_split
from sklearn.base import clone
from DataLoader import DataLoader
from DataSplitter import DataSplitter
from PipelineBuilder import Pipeline
from CrossValidation import CrossValidation

In [2]:
## Loading data
data_loader = DataLoader(path_train="../data/train.csv", path_eval="../data/validation.csv", path_test="../data/test.csv")
train, validation, test = data_loader.load()
train.shape, validation.shape, test.shape

((29000, 2), (1000, 2), (10000, 2))

In [3]:
## Splitting data
data_splitter = DataSplitter(src_language='english', target_language='portuguese')
X_train, y_train = data_splitter.split(train)
X_val, y_val = data_splitter.split(validation)
X_test, y_test = data_splitter.split(test)

In [4]:
## Reloading model
pipe = Pipeline.load("translatorTransformer1.pt")
pipe

,tokenizer_method,'full words'
,max_length,30
,vocab_size,4000
,embedding_dim,256
,n_heads,8
,num_encoder_layers,4
,num_decoder_layers,4
,dropout,0.1
,max_length_decoded,30
,lr,0.0005
,epochs,120


In [5]:
preds = pipe.predict(X_test)
preds_df = pd.DataFrame({'english': X_test.iloc[:, 0].values, 'portuguese': y_test.iloc[:, 0].values, 'translation': preds})
preds_df.iloc[500:550, :]

Full Words
7.0843
[ 7. 10. 11. 15.]
time cleaning and encoding test:  3.672912359237671
Training Activated ? False
time predicting test:  198.02525544166565
Time decodig test:  0.06394147872924805


,english,portuguese,translation
500,I'll get my bag.,Pegarei minha bolsa.,Eu vou abrir a minha bolsa .
501,I prayed for God's help.,Orei pela ajuda de Deus.,Eu tenho ajuda .
502,Tom is unenthusiastic.,Tom está sem entusiasmo.,Tom é .
503,Stop wasting money.,Pare de desperdiçar dinheiro.,Pare de gastar dinheiro .
504,"Study hard, and you'll succeed.",Se esforce nos estudo que você terá sucesso.,", e senhores , conseguirá ."
505,Tom looked very concerned.,Tom parecia muito preocupado.,Tom parecia muito preocupado .
506,I guess I'm wrong.,Acho que estou errado.,Eu acho que estou errado .
507,Tom is willing to do that for you.,Tom está disposto a fazer isso por você.,O Tom está disposto a fazer isso por você .
508,You hurt me.,Você me machucou.,Vocês me machucaram .
509,Where is my pencil?,Onde está o meu lápis?,Onde está o meu lápis ?


In [15]:
phrases = ['I love watching movies',
           "I'm not sure how many people understand what this means.",
           "Don't eat this delicious pizza.",
           "Let's go!",
           "Let's jump into the pool."
          ]
english_df = pd.DataFrame({'english': phrases})
pipe.predict(english_df)

Full Words
6.0
[ 6.   9.  10.  10.8]
time cleaning and encoding test:  0.0043146610260009766
Training Activated ? False
time predicting test:  0.0822610855102539
Time decodig test:  0.0


['Eu adoro assistir ?',
 'Não tenho certeza de pessoas pessoas quem sabes que o Tom gosta .',
 'Não coma comer este camisa .',
 'Vamos voltar !',
 'Vamos na piscina .']

In [7]:
## Reloading model
pipe = Pipeline.load("translatorLSTM1.pt")
pipe

,tokenizer_method,'full words'
,max_length,30
,model_name,'LSTM'
,embedding_dim,512
,hidden_dim,512
,num_layers,2
,dropout,0.3
,teacher_forcing,0.5
,max_length_decoded,30
,lr,0.0005
,epochs,100


In [8]:
preds = pipe.predict(X_test)
preds_df = pd.DataFrame({'english': X_test.iloc[:, 0].values, 'portuguese': y_test.iloc[:, 0].values, 'translation': preds})
preds_df.iloc[500:550, :]

Full Words
7.0843
[ 7. 10. 11. 15.]
time cleaning and encoding test:  2.470521926879883
Training Activated ? False
time predicting test:  38.54828882217407
Time decodig test:  0.06145453453063965


,english,portuguese,translation
500,I'll get my bag.,Pegarei minha bolsa.,Eu vou cair a minha sacola .
501,I prayed for God's help.,Orei pela ajuda de Deus.,Eu ajuda para o .
502,Tom is unenthusiastic.,Tom está sem entusiasmo.,Tom é .
503,Stop wasting money.,Pare de desperdiçar dinheiro.,Pare de gastar dinheiro .
504,"Study hard, and you'll succeed.",Se esforce nos estudo que você terá sucesso.,com mel e você seja bem .
505,Tom looked very concerned.,Tom parecia muito preocupado.,Tom parecia estar muito preocupado .
506,I guess I'm wrong.,Acho que estou errado.,Eu acho que estou errado .
507,Tom is willing to do that for you.,Tom está disposto a fazer isso por você.,O Tom está disposto a fazer isso por você .
508,You hurt me.,Você me machucou.,Você me .
509,Where is my pencil?,Onde está o meu lápis?,Onde está meu lápis ?


In [9]:
phrases = ['A young boy is sat on a chair',
           'Soccer players do not understand math',
           'Soccer players are playing soccer',
          ]
english_df = pd.DataFrame({'english': phrases})
pipe.predict(english_df)

Full Words
6.333333333333333
[6.   7.6  7.8  7.96]
time cleaning and encoding test:  0.026250123977661133
Training Activated ? False
time predicting test:  0.04908871650695801
Time decodig test:  0.0


['A garota é jovem em cadeira .',
 'O não consigo entender .',
 'Os futebol estão jogando futebol .']